### ISSUE TITLE
Health: Final Test Review

### ISSUE THREAD

**Issue by JunyiSun** [OpenLiberty/guide-microprofile-health#41]
- Highlights in the nav bar look a bit weird?  **[Fixed]**

- "The system and inventory services can be found at the following URLs: - http://localhost:9080/system/properties - http://localhost:9080/inventory/systems"
The layout here is incorrect, we need to use new line for each URL **[fixed]**

- What is the data property here? Why for InventoryResource it's called `services`, and for SystemResource it's called `default server`? You explained all other fields but not this one in Try what you'll learn **(Okay we can worry about it later)** 
@eveline any suggestions? + why we do not have the output anymore @Kubik42?

```
{
"checks": [
{
"data": {
"services": "available"
},
"name": "InventoryResource",
"state": "UP"
},
{
"data": {
"default server": "available"
},
"name": "SystemResource",
"state": "UP"
}
],
"outcome": "UP"
}
```

- Update mpConfig-1.1 to 1.2 in the server.xml, also change pom.xml **[fixed]**
```
  <dependency>
      <groupId>org.eclipse.microprofile.config</groupId>
      <artifactId>microprofile-config-api</artifactId>
      <version>1.1</version> 
      <scope>provided</scope>
```
to `<version>1.2</version>` . Remember to do both in start/ and finish/

- "All services must provide an implementation of the HealthCheck interface, which will be used to verify their healthiness. " healthiness to health? **[fixed]**

- "This time, you are checking whether or not the service is in maintenance or if it’s down."
Too many disjunctions here, make the sentence ambiguous. **[Fixed]**

- "To check that the service is down, simply make a HTTP GET request the system service and check the status returned by the response."
Should be "To check if the service is down" ? cuz it might not be down **[fixed]**

- You are missing the paragraph after the testing result, which stating what you can do to make the tests fail **[What are we deciding on this?]**

**Comment by yeekangc** [comment]
@JunyiSun, are you sure you looked at the latest in master?  The test site might not have been refreshed.  Please double check with @evelinec and @Kubik42.

**Comment by yeekangc** [comment]
We have issue with the portion where we are asking users to make the tests fail.  It can be dropped for now and be looked at later.

**Comment by JunyiSun** [comment]
@yeekangc double checked, those issues still existed in the latest master branch.

**Comment by yeekangc** [comment]
Thanks.  @Kubik42 can take a look.

I am pretty sure we have dropped the sample `/health` response from the guide.

**Comment by JunyiSun** [comment]
@yeekangc What sample /health response are you referring to btw?

**Comment by JunyiSun** [comment]
@yeekangc oh, if you are referring to the data response, then I am pretty sure it has not been dropped in the current master branch yet.

**Comment by evelinec** [comment]
@lauracowen requested we add the sample output in the guide.

**Comment by yeekangc** [comment]
@JunyiSun:

```{
"checks": [
{
"data": {
"services": "available"
},
"name": "InventoryResource",
"state": "UP"
},
{
"data": {
"default server": "available"
},
"name": "SystemResource",
"state": "UP"
}
],
"outcome": "UP"
}```

@evelinec, I understand there was a request but if it doesn't add but subtract, we take it out and address it properly later (via #40).

**Comment by yeekangc** [comment]
@JunyiSun, please call out clearly what @Ahmad-Ayyoub should address now.  The rest can go into #40.

At best, only item 1, 2, 4, 5, 6, 7 by my count.

**Comment by Ahmad-Ayyoub** [comment]
-Ok so we will add the output after we address it out. @evelinec any suggestions on what do to for the data property? 

- You are missing the paragraph after the testing result, which stating what you can do to make the tests fail **[What are we deciding on this?]**

**Comment by yeekangc** [comment]
Any suggestion or thought regarding these, @Ahmad-Ayyoub?  Thanks.

**Comment by Ahmad-Ayyoub** [comment]
For Data Property: Previously it was empty. But when @lauracowen suggested to add the output, @evelinec suggested to add something in the data field (which what we have now). My suggestion is to just take it off since there is no actual useful info to display for now.

For these tests, we can say:
To test your knowledge of the guide, try to change the "logic" of or some "info" from the application and investigate the test case(s) failure(s) after that change. 

this is just a draft

**Comment by yeekangc** [comment]
Thank you, @Ahmad-Ayyoub.

We currently do not show the health response in the guide.  The response can be included if done right.  At least, the names and values can be made more meaningful.  Similarly, the sample response can be better described than what was there.

The paragraph on the tests was removed intentionally IIRC since it didn't add to the guide.  If we shall put it back, it needs to be better than what is suggested.

**Comment by Ahmad-Ayyoub** [comment]
So what about this:

```
{
    "checks": [
          {
             "data": {
             "dependency": "default server"
          },
              "name": "System",
              "state": "UP"
          },
          {
             "data": {
             "dependency": "{config property: inMaintenance, service: System}
          },
             "name": "Inventory",
              "state": "UP"
          }
     ],
     "outcome": "UP"
}
```

**Comment by lauracowen** [comment]
I've not followed this whole conversation or thread of changes but here's the reason I asked about output...

I added health check to an app and I had something in the wrong place in the code so it wasn't working (I can't remember what exactly). When the app ran I got only

```
{
    "checks": [
       
     ],
     "outcome": "UP"
}
```

(or something like that - I can't remember exactly). So I could see that healthcheck was telling me something and I could tell that something was missing but I didn't know what should've been within the `[ ]`. It made it quite difficult to debug what was wrong because I didn't know what the 'correct' output should be. If I had, it would've been clearer that the app was working okay but that the individual microservices within the app were not. (I think I was missing an annotation or a scope was set wrongly or something in the end.)

Hope that helps... :)

**Comment by yeekangc** [comment]
@lauracowen, thank you.

No issue for a sample to be included.  Just need to work out what should be in and how to best present it.

**Comment by Ahmad-Ayyoub** [comment]
The team discussed and we agreed on the second option with explaining why we left the data field empty.

**Comment by yeekangc** [comment]
That's the minimum.

Including data is fine provided that we do better than what we have.  Good to have it if we can do it.

**Comment by evelinec** [comment]
@Ahmad-Ayyoub we don't need to explain why we left the data field empty, but what are they and perhaps how they can be used, in a short sentence or two. 

FYI, as we discussed during scrum today, and after looking into this field closely. It can actually have functionality. Since our guide is not making use of the data field, we'd definitely leave it empty. Add an explanation in the guide is good.

**Comment by yeekangc** [comment]
#40 made a note of this too.  @Ahmad-Ayyoub @JunyiSun, you folks can discuss further and come back with a proposal.
